dssimchosen <- list(density(dssim[,5]), density(dssim[,15]), density(dssim[,45]), density(dssim[,120]))
xs <- c(mapply(function(d) d$x, dssimchosen))
ys <- c(mapply(function(d) d$y, dssimchosen))
plot(dssimchosen[[1]], xlab='usd', ylab='dens', xlim=c(min(xs),max(xs)), ylim=c(min(ys),max(ys)), col='blue', main='')
lines(dssimchosen[[2]], col='brown')
lines(dssimchosen[[3]], col='orange')
lines(dssimchosen[[4]], col='green')
abline(v=totalspace, col='red')
legend('top', c('5 day', '15 days', '45 days', '120 days'), fill=c('blue', 'brown', 'orange', 'green'))
