
import os

Import(['env'])

env.Program('hasbug.c', CPPFLAGS='-g')

env.Command('r1w3_n4_results.csv', ['box'], '$SOURCE -r 1 -w 3 -n 4 --output-results $TARGET', chdir=False)
env.Command('r1w3_n4_results.t2t', ['r1w3_n4_results.csv'], './tools/csvt2ttable $SOURCE $TARGET')
env.Depends('r1w3_n4_results.t2t', '../../tools/csvt2ttable')
env.MAKO('r1w3_n4_results.t2t', MAKOFLAGS = '-t htmlbare')

for rw in [(1, 3), (1, 2), (1, 1)]:
    b = 'r%dw%d_n4_probabilities' % rw
    env.Command(b+'.csv', ['box'], '$SOURCE -r %d -w %d -n 4 --output-probabilities $TARGET' % rw, chdir=False)
    env.Command(b+'.t2t', [b+'.csv'], './tools/csvt2ttable $SOURCE $TARGET')
    env.Depends(b+'.t2t', '../../tools/csvt2ttable')
    env.Depends('index.bhtml', b+'.t2t')

env.MAKO('index.t2t', MAKOFLAGS = '-t htmlpage')

env.Command('r1w3_dist.png', 'pdistplot.R', '$SOURCE 1 3 $TARGET')
env.Command('r1w3_dens.png', 'pdensplot.R', '$SOURCE 1 3 $TARGET')

env.Command('boxballs.png', 'boxballs.pov', 'runsilent povray ${SOURCE.file} -V +FN +O${TARGET.file} +Q11 +AM2 +H240 +W320 -D', chdir=True)

env.Command('pdens_many.png', 'pdensplot_many.R', '$SOURCE 1 3 $TARGET')

