language: python
before_install:
  # static checkers:
  - pip install flake8 py3kwarn
script:
  - nosetests --with-doc --exe
  # Test if we .gitignore test files:
  - TMP=$(tempfile)
  - git ls-files . --exclude-standard --others | tee "$TMP"
  - if test -s "$TMP"; then false; else true; fi
  # Test if we .gitignore any tracked files:
  - git ls-files -i --exclude-standard | tee "$TMP"
  - if test -s "$TMP"; then false; else true; fi
  # static checkers:
  - flake8 . SConstruct **/SConscript
  - py3kwarn . SConstruct **/SConscript
