---
language: generic
install: docker build -t lpenz.github.io .
script:
  - docker run -it --rm -v $PWD:/home/user/work -e MY_UID=$UID lpenz.github.io
  # Test if we .gitignore test files:
  - TMP=$(tempfile)
  - git ls-files . --exclude-standard --others | tee "$TMP"
  - if test -s "$TMP"; then false; else true; fi
  # Test if we .gitignore any tracked files:
  - git ls-files -i --exclude-standard | tee "$TMP"
  - if test -s "$TMP"; then false; else true; fi

