#!/bin/bash

findfiles=( find . -type f '(' -not -path './external/*' ')' '(' -not -path './.git/*' ')' )
pyfilter=( '(' -name '*.py' -o -name SConstruct -o -name SConscript ')' )

set -x -e -o pipefail

nosetests --with-doc --exe
"${findfiles[@]}" "${pyfilter[@]}" -exec flake8 {} +
"${findfiles[@]}" -exec grep -lI '[#]!/usr/bin/python' {} + | xargs flake8
"${findfiles[@]}" "${pyfilter[@]}" -exec py3kwarn {} +
"${findfiles[@]}" -exec grep -lI '[#]!/usr/bin/python' {} + | xargs py3kwarn
scons

