#!/bin/bash

set -x -e -o pipefail

nosetests --with-doc --exe
find . \( -name '*.py' -o -name SConstruct -o -name SConscript \) -exec flake8 {} +
grep -nlIr '[#]!/usr/bin/python' . | xargs flake8
find . \( -name '*.py' -o -name SConstruct -o -name SConscript \) -exec py3kwarn {} +
grep -nlIr '[#]!/usr/bin/python' . | xargs py3kwarn
scons

