#!/bin/bash

findfiles=( find . -type f '(' -not -path './external/*' ')' '(' -not -path './.git/*' ')' )
pyfilter=( '(' -name '*.py' -o -name SConstruct -o -name SConscript ')' )

set -x -e -o pipefail

nosetests3 --with-doc --exe
"${findfiles[@]}" "${pyfilter[@]}" -exec flake8 {} +
"${findfiles[@]}" -exec grep -lI '[#]!/usr/bin/python' {} + | xargs flake8
scons

