import os

pjoin = os.path.join

if False:
    Import = None
    env = None
Import(["env"])

env["PANDOC_TEMPLATE"] = env.File("../../templates/pandoctoc.tmpl.html")
env.PANDOC(
    "_index.bhtml.mako",
    "index.md",
    PANDOCFLAGS="-N -s -t html --toc",
)
env.MAKO("index.html", "_index.bhtml.mako", MAKOFLAGS="-t htmlpage -r '#dollar#=$'")
env.HTMLSITEFILES.add("articles/github-project-struct/index.html")
