
import os

Import(['env'])

env.Command('pointplot.png', 'main.R', 'Rscript ${SOURCE.file}', chdir=1)
env.Depends('pointplot.png', 'init.R')
env.SideEffect('lmplot.png', 'pointplot.png')
env.SideEffect('lm.txt', 'pointplot.png')
env.SideEffect('lmsummary.txt', 'pointplot.png')
env.SideEffect('lmrandsummary.txt', 'pointplot.png')

env.MAKO('index.t2t', MAKOFLAGS = '-t base')
env.Depends('index.html', '../index.t2t')
env.Depends('index.html', '../../index.t2t')

