#!/bin/sh

D=${1?}
shift
LIST=${1?}
shift

echo -n > $D

PRE=\`\`\`

cat <<END >> $D
Debian



To use the debian repository behind this page, add the following line in 
///etc/apt/sources.list//:

$PRE
$(cat $LIST)
$PRE

If you really trust me, you can add the GPG key I sign the repository with by issuing:
$PRE
wget -O - http://lpenz.org/lpenz_2010.asc | apt-key add -
$PRE


The following utilities are available in the repository:

END

for i in "$@"; do
	APP=$(sed -n 's/^Source: \(.*\)/\1/p' $i)
	DESCR=$(sed -n "/^Description:/,+1s/^ $APP \+- \(.*\)$/\1/p" $i)
	echo - [$APP http://github.com/lpenz/$APP]: $DESCR >> $D
done

cat <<END >> $D


They are all free software. Their source code can be found in
http://github.com/lpenz, along with other projects that are not debianizable.

END

