#!/bin/sh

D=$1
shift

cat <<END > $D
lpenz Debian packages



The following utilities are available in my github repository page:
http://github.com/lpenz/:

END

for i in incoming/*.changes; do
	APP=$(sed -n 's/^Source: \(.*\)/\1/p' $i)
	DESCR=$(sed -n "/^Description:/,+1s/^ $APP \+- \(.*\)$/\1/p" $i)
	echo - [$APP http://www.github.com/lpenz/$APP]: $DESCR >> $D
done

cat <<END >> $D


They are also available in a debian repository, you can use it by including the
following line in ///etc/apt/sources.list//:

\`\`\`
END
sed '/^$/d' lpenz.list >> $D
cat <<-END >> $D
\`\`\`


END

