
import os
import glob

Import(['env', 'htmlsitefiles'])

if False:
    env.Command('dists/lpenz/main/binary-i386/Packages',  glob.glob('packages/*.deb'), '(set -e; cd debian; dpkg-scanpackages packages) > ${TARGET.file}.tmp && mv ${TARGET.file}.tmp ${TARGET}')
    env.Command('dists/lpenz/main/source/Sources',        glob.glob('packages/*.dsc'), '(set -e; cd debian; dpkg-scansources  packages) > ${TARGET.file}.tmp && mv ${TARGET.file}.tmp ${TARGET}')
    env.Command('dists/lpenz/main/binary-i386/Packages.bz2', 'dists/lpenz/main/binary-i386/Packages' , '(set -e; cat $SOURCE | bzip2 -9c) > ${TARGET.file}.tmp && mv ${TARGET.file}.tmp ${TARGET}')
    env.Command('dists/lpenz/main/source/Sources.bz2',       'dists/lpenz/main/source/Sources'       , '(set -e; cat $SOURCE | bzip2 -9c) > ${TARGET.file}.tmp && mv ${TARGET.file}.tmp ${TARGET}')
    #env.Command('Contents.gz',  glob.glob('incoming/*.deb'), 'apt-ftparchive contents . | gzip -9c > ${TARGET.file}.tmp && mv ${TARGET.file}.tmp ${TARGET.file}', chdir=1)
    env.Command('dists/lpenz/Release',   ['dists/lpenz/main/binary-i386/Packages.bz2', 'dists/lpenz/main/source/Sources.bz2', 'lpenz-apt-release.conf'], '(set -e; apt-ftparchive -c debian/lpenz-apt-release.conf release debian/dists/lpenz) > ${TARGET.file}.tmp && mv ${TARGET.file}.tmp ${TARGET}')
    env.Command('dists/lpenz/Release.gpg', 'dists/lpenz/Release', 'gpg --output ${TARGET} -ba ${SOURCE}')

indexbuild = env.File('indexbuild')
env.Command('index.t2t', ['lpenz.list']+env.Glob('packages/*.changes'), indexbuild.abspath + ' ${TARGET} ${SOURCES}')
env.Depends('index.t2t', indexbuild)

env.MAKO('index.t2t', MAKOFLAGS='-t base')
htmlsitefiles.add('debian/index.html')

