#!/usr/bin/env python3
'''Create gnupg logs for gpg article'''

import sys
import os
import re
import subprocess
from contextlib import contextmanager
import tempfile
import pexpect
import argparse
import yaml
from io import StringIO

pjoin = os.path.join


@contextmanager
def chdir(d):
    old = os.getcwd()
    os.chdir(d)
    yield
    os.chdir(old)


class Session(pexpect.spawn):
    def __init__(self, env, preproc=None):
        env_ = {'PS1': '\\$ ', 'PS2': '=>'}
        env_.update(env)
        pexpect.spawn.__init__(self,
                               'bash', ['--norc'],
                               encoding='utf-8',
                               timeout=10,
                               env=env_)
        self.preproc = preproc
        self._prompt = u'\\$ $'
        self._logfd = None
        self._pending = ''
        self.waitready()
        self.sendwait('stty cols 9999')

    def log(self, s):
        s = s.replace('\r', '')
        if self.preproc:
            s = self.preproc(s)
        sys.stdout.write(s)
        if self._logfd:
            self._logfd.write(s)

    def process(self):
        self.log(self._pending)
        m = self.match
        i1, i2 = m.span()
        self.log(m.string[0:i1])
        self._pending = m.string[i1:]
        # print(('lpenz', m.string[0:i1], m.string[i1:]))

    def waitready(self, prompt=None):
        prompt = prompt or self._prompt
        self.expect(prompt)
        return self.process()

    @contextmanager
    def logging(self):
        fd = StringIO()
        self._logfd = fd
        yield fd
        self._logfd = None
        fd.close()

    @contextmanager
    def prompt(self, prompt):
        oldprompt = self._prompt
        self._prompt = prompt
        yield
        self._prompt = oldprompt

    def sendwait(self, cmd, prompt=None):
        self.send(cmd + '\r')
        return self.waitready(prompt=prompt)

    def trimprompt(self, string):
        return re.sub(self._prompt, '', string)

    def done(self):
        self.send('exit\r')
        self.expect(pexpect.EOF)
        self.wait()


@contextmanager
def bgprocess(cmd):
    r = subprocess.Popen(cmd,
                         stdout=subprocess.DEVNULL,
                         stderr=subprocess.DEVNULL)
    yield
    r.kill()
    r.wait()


def do_main(gpgconf, outputfile):
    data = {}
    with tempfile.TemporaryDirectory() as tmpdir:
        env = {
            'GNUPGHOME': tmpdir,
        }
        # Create gpg.conf
        with open(pjoin(tmpdir, 'gpg.conf'), 'w') as fd:
            with open(gpgconf, 'r') as fd_gpgconf:
                fd.write(fd_gpgconf.read())
            fd.write('pinentry-mode loopback\n')
        # Start sesssion
        p = Session(env=env, preproc=lambda s: s.replace(tmpdir + '/', ''))
        passphrase = 'asdfasdf'
        with bgprocess(['find', '/', '-type', 'f']):
            # Create key:
            with p.logging() as logfd:
                p.send('gpg --quick-gen-key '
                       '\'Leandro Lisboa Penz <lpenz@lpenz.org>\' '
                       'default default 0\r')
                p.waitready(prompt=u': $')
                p.sendwait(passphrase)
                genkey = logfd.getvalue()
                genkey = re.sub('Enter passphrase: *', 'Enter passphrase:\n',
                                genkey)
                data['genkey'] = genkey
        # Figure out uuid:
        m_uuid = re.search(
            u'pub\\s+[^/]+/(?P<uuid>[0-9A-F]+) [0-9-]+ \\[SC\\]', genkey)
        assert m_uuid
        uuid = m_uuid.group('uuid')
        data['uuid'] = uuid
        # Go to editkey prompt:
        with p.prompt('gpg> $'):
            with p.logging() as logfd:
                p.sendwait('gpg --edit-key %s' % uuid)
                data['gpgedit'] = logfd.getvalue()
            with p.logging() as logfd:
                with p.prompt(': $'):
                    # adduid
                    p.sendwait('adduid')
                    p.sendwait('Leandro Lisboa Penz')
                    p.sendwait('llpenz@gmail.com')
                    p.sendwait('', '\\? $')
                    p.sendwait('O')
                p.sendwait(passphrase)
                data['adduid'] = logfd.getvalue()
            with p.logging() as logfd:
                p.sendwait('uid 1')
                p.sendwait('primary')
                data['uidprimary'] = logfd.getvalue()
            with p.logging() as logfd:
                with p.prompt('\\?[ ?0-9()yN/]* $'):
                    p.sendwait('addkey')
                    p.sendwait('4')
                    p.sendwait('')
                    p.sendwait('')
                    p.sendwait('y')
                p.sendwait('y', ': $')
                p.sendwait(passphrase)
                data['addkey'] = logfd.getvalue()
        # Exiting
        p.sendwait('save')
        p.done()
    with open(outputfile, 'w') as fd:
        yaml.dump(data, fd, indent=4)


def main():
    parser = argparse.ArgumentParser(description='Process some integers.')
    parser.add_argument('gpgconf')
    parser.add_argument('outputfile')
    args = parser.parse_args()
    do_main(args.gpgconf, args.outputfile)


if __name__ == '__main__':
    main()
