#!/usr/bin/env python3
'''Create gnupg logs for gpg article'''

import sys
import os
import re
import subprocess
from contextlib import contextmanager
import tempfile
import pexpect
import argparse
import yaml

pjoin = os.path.join


@contextmanager
def chdir(d):
    old = os.getcwd()
    os.chdir(d)
    yield
    os.chdir(old)


class Session(pexpect.spawn):
    def __init__(self, env, preproc=None):
        env_ = {'PS1': '\\$ ', 'PS2': '=>'}
        env_.update(env)
        pexpect.spawn.__init__(self,
                               'bash', ['--norc'],
                               encoding='utf-8',
                               env=env_)
        self.preproc = preproc
        self.prompt = u'\\$ $'
        self.wait_prompt()
        self.runcmd('stty cols 9999')

    def process(self):
        m = self.match
        s = m.string.replace('\r', '')
        if self.preproc:
            s = self.preproc(s)
        sys.stdout.write(s)
        return s

    def wait_prompt(self, prompt=None):
        prompt = prompt or self.prompt
        self.expect(prompt)
        return self.process()

    def runcmd(self, cmd):
        self.send(cmd + '\r')
        self.wait_prompt()

    def done(self):
        self.send('exit\r')
        self.expect(pexpect.EOF)
        self.wait()


def do_main(gpgconf, outputfile):
    data = {}
    with tempfile.TemporaryDirectory() as tmpdir:
        env = {
            'GNUPGHOME': tmpdir,
        }
        with open(pjoin(tmpdir, 'gpg.conf'), 'w') as fd:
            with open(gpgconf, 'r') as fd_gpgconf:
                fd.write(fd_gpgconf.read())
            fd.write('pinentry-mode loopback\n')
        p = Session(env=env, preproc=lambda s: s.replace(tmpdir + '/', ''))
        genkey = []
        r = subprocess.Popen(['find', '/', '-type', 'f'],
                             stdout=subprocess.DEVNULL,
                             stderr=subprocess.DEVNULL)
        p.send('gpg --quick-gen-key '
               '\'Leandro Lisboa Penz <lpenz@lpenz.org>\' '
               'default default 0\r')
        genkey.append(p.wait_prompt(prompt=u': $'))
        p.send('asdfasdf\n')
        genkey.append(p.wait_prompt())
        r.kill()
        r.wait()
        genkey = ''.join(genkey)
        genkey = re.sub('Enter passphrase: *', 'Enter passphrase:\n', genkey)
        genkey = re.sub('[$ ]+$', '', genkey)
        data['genkey'] = genkey

        m_uuid = re.search(
            u'pub\\s+[^/]+/(?P<uuid>[0-9A-F]+) [0-9-]+ \\[SC\\]', genkey)
        assert m_uuid
        data['uuid'] = m_uuid.group('uuid')
        p.done()
    with open(outputfile, 'w') as fd:
        yaml.dump(data, fd, indent=4)


def main():
    parser = argparse.ArgumentParser(description='Process some integers.')
    parser.add_argument('gpgconf')
    parser.add_argument('outputfile')
    args = parser.parse_args()
    do_main(args.gpgconf, args.outputfile)


if __name__ == '__main__':
    main()
