import os
pjoin = os.path.join

if False:
    Import = None
    env = None
Import(['env'])

env.PANDOC('index.bhtml.mako', 'index.md')
env.MAKO('index.html', 'index.bhtml.mako', MAKOFLAGS='-t htmlpage')
env.HTMLSITEFILES.add('articles/luksfile/index.html')
