
import os
import glob

Import(['env'])

# Whatsnew feed:
env.MAKO('whatsnew.xml', 'whatsnew.feed')
env.Depends('whatsnew.xml', '../templates/feed.xml')

# Articles feed:
env.MAKO('articles.xml', 'articles.feed')
env.Depends('articles.xml', '../templates/feed.xml')

for i in glob.glob('../articles/*'):
    if not os.path.isdir(i):
        continue
    env.Depends('articles.xml', os.path.join(i, 'index.html'))

