
import os
import glob

Import(['env'])

# Whatsnew feed:
env.MAKO('whatsnew.xml', 'whatsnew.feed')
env.Depends('whatsnew.xml', '../templates/feed.xml')

# Articles feed:
env.MAKO('articles.xml', 'articles.feed')
env.Depends('articles.xml', '../templates/feed.xml')

