<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>
<title>$title$</title>
<link rel="stylesheet" type="text/css" href="$top$/base-min.css" />
<link rel="stylesheet" type="text/css" href="$top$/style.css" />
<link rel="shortcut icon" href="$top$/favicon.ico" />
</head>
<body>
<div id="header">
	<div id="logo">
		<a href="$top$/index.html"><img alt="Avulsos by Penz" src="$top$/logo.png" /></a>
	</div>
	<div id="title">
		$breadcrumbs$
	</div>
	<ul id="nav">
		<li><a href="$top$/articles/index.html">Articles</a></li>
		<li><a href="$top$/debian/index.html">Debian</a></li>
		<li><a href="$top$/aboutme/index.html">About me</a></li>
	</ul>
</div>
<div id="contents">
	<h1 id="title">$title$</h1>
$content$
</div>
<div id="footer">
		<a rel="license" href="http://creativecommons.org/licenses/by-sa/3.0/"><img alt="Creative Commons License" style="border-width:0" src="http://i.creativecommons.org/l/by-sa/3.0/88x31.png" /></a>
		This work by <span xmlns:cc="http://creativecommons.org/ns#" property="cc:attributionName">Leandro Lisboa Penz</span> is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/3.0/">Creative Commons Attribution-ShareAlike 3.0 Unported License</a>.
</div>
<script type="text/javascript"> var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www."); document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E")); </script> <script type="text/javascript"> try { var pageTracker = _gat._getTracker("UA-4182011-2"); pageTracker._trackPageview(); } catch(err) {}</script>
</body>
</html>
<!-- vim: ft=html
-->
