
import os

Import(['env'])

env.R('main.RData', 'main.R')
env.Depends('main.RData', 'duinfospike.dat')

for i in ['delta', 'deltabox', 'deltakd', 'daysleft', 'lm', 'df0density','df0cumsum']:
    env.Command(i+'.png', ['main.RData', 'plot.R', i+'plot.R'], './plot.R '+i, chdir=1)

for i in ['delta']:
    env.Command(i+'summary.txt', ['main.RData', i+'summary.R'], './%ssummary.R ' % i, chdir=1)

env.MAKO('index.t2t', MAKOFLAGS = '-t base')

