
import os

Import(['env'])

env.R('main.RData', 'main.R')

for i in ['deltabox', 'daysleft', 'lm', 'df0date','df0density','df0cumsum']:
    env.Command(i+'.png', ['main.RData', 'plot.R', i+'plot.R'], './plot.R '+i, chdir=1)

env.MAKO('index.t2t', MAKOFLAGS = '-t base')

