#!/usr/bin/python3

import sys
import os
import csv


def main():
    from optparse import OptionParser

    parser = OptionParser("usage: %prog <input> <output>")
    opts, args = parser.parse_args(sys.argv[1:])
    if len(args) != 2:
        parser.error("wrong number of arguments")  # Will exit

    ifilename = args[0]
    ofilename = args[1]

    o = open(ofilename + ".tmp", "w")
    o.write("\n\n\n\n")
    first = True
    for line in csv.reader(open(ifilename)):
        if first:
            o.write("|")
            first = False
        o.write("| " + " | ".join(line) + " |\n")
    o.close()
    os.rename(ofilename + ".tmp", ofilename)


if __name__ == "__main__":
    main()
