#!/usr/bin/python

import sys
import yaml
import os
import re


def yamlget(d):
    yfilename = os.path.join(d, 'info.yaml')
    if not os.path.isfile(yfilename):
        return {}
    return yaml.load(open(yfilename).read())


def templated(infilename, template, y):
    from tempfile import TemporaryFile
    from os.path import isfile
    from subprocess import Popen

    if not isfile(infilename):
        raise SystemExit("error: can't find %s" % infilename)
    infd = open(infilename)
    outfd = TemporaryFile()
    if template:
        outfd.write('<%%inherit file="%s.html"/>\n' % template)
    imgcenterre = re.compile('^\s*<center>(<img[^>]+>)</center>\s*$')
    pipfrem = re.compile('(.*)<p>\s*</p>(.*)')
    skipnext = False
    for l in infd:
        m = imgcenterre.match(l)
        if m:
            l = '</p>\n<center>%s</center>\n' % m.group(1)
            outfd.write(l)
            skipnext = True
            continue
        m = pipfrem.match(l)
        if m:
            l = m.group(1)
        if not skipnext:
            outfd.write(l)
        skipnext = False
    outfd.seek(0)
    return outfd.read()


def makorender(data, y):
    from mako.template import Template
    from mako.lookup import TemplateLookup

    lookup = TemplateLookup(['templates'])
    return Template(data, lookup=lookup).render(**y)


def dirscalc(infilename):
    dirname =  os.path.join('.', os.path.dirname(infilename))
    top = ''
    breadcrumbs = []
    dirs = dirname.split(os.sep)
    dirs = [ d for d in dirs if d != '' ]
    lvl = len(dirs) - 1
    yt = yaml.load(open('infotree.yaml').read())
    yc = yt
    p = ''
    for d in dirs:
        if d != '.':
            yc = yc['sub'][d]
        p = os.path.join(p, d)
        i = 'index.html'
        for l in range(lvl, 0, -1):
            i = os.path.join('..', i)
        breadcrumbs.append('<a href="%s">%s</a>' % (i, yc['title']))
        if lvl > 0:
            top = os.path.join(top, '..')
        lvl = lvl - 1
    if top == '':
        top = '.'
    return top, ' &gt; '.join(breadcrumbs)


def main(argv=None):
    if argv is None:
        import sys
        argv = sys.argv

    from optparse import OptionParser

    parser = OptionParser("usage: %prog <input> <output>")
    parser.add_option("-t", "--template", dest="template", help="Template to use, if any")
    opts, args = parser.parse_args(argv[1:])
    if len(args) != 2:
        parser.error("wrong number of arguments") # Will exit

    infilename = args[0]
    outfilename = args[1]

    indirname = os.path.dirname(infilename)

    y = yamlget('.')
    y.update(yamlget(indirname))
    if y.has_key('disqus') and not y.has_key('disqus_id'):
        y['disqus_id'] = os.path.basename(indirname)
    y['top'], y['breadcrumbs'] = dirscalc(infilename)
    y['url'] = '%s/%s' % (y['home'], indirname)
    if indirname != '':
        y['url'] = y['url'] + '/'
    y['url'] = y['url'] + 'index.html'
    htmlstr = templated(infilename, opts.template, y).replace('$cwd$/', '')
    out = open(outfilename, 'w')
    out.write(makorender(htmlstr, y))


if __name__ == "__main__":
    main()

