#!/usr/bin/python3

import sys
import re
import os
from tempfile import TemporaryFile
from subprocess import Popen


def t2thtml(infilename):
    if not os.path.isfile(infilename):
        raise SystemExit("error: can't find %s" % infilename)
    t2toutfd = TemporaryFile(mode="w+", encoding="utf-8")
    try:
        t2t = Popen(
            [
                "txt2tags",
                "-t",
                "xhtml",
                "--config-file",
                "t2tconfig",
                "-H",
                "-i",
                infilename,
                "-o",
                "-",
            ],
            stdout=t2toutfd,
        )
        retcode = t2t.wait()
        if retcode < 0:
            sys.stderr.write("Child was terminated by signal %d\n" % -retcode)
            sys.exit(1)
        elif retcode != 0:
            sys.stderr.write("Child returned %d\n" % retcode)
            sys.exit(1)
    except OSError as e:
        sys.stderr.write("Execution failed: %s\n" % str(e))
        sys.exit(1)
    t2toutfd.seek(0)
    return t2toutfd


def main():
    from optparse import OptionParser

    parser = OptionParser("usage: %prog <input> <output>")
    opts, args = parser.parse_args(sys.argv[1:])
    if len(args) != 2:
        parser.error("wrong number of arguments")  # Will exit

    infilename = args[0]
    outfilename = args[1]

    t2toutfd = t2thtml(infilename)

    outfd = open(outfilename, "w")

    pipfrem = re.compile(r"(.*)<p>\s*</p>(.*)\s*$")
    for line in t2toutfd:
        line = line.rstrip()
        m = pipfrem.match(line)
        if m:
            line = m.group(1) + " " + m.group(2)
        outfd.write(line)
        outfd.write("\n")


if __name__ == "__main__":
    main()
