#!/bin/sh

SRC=${1?}
DST=${2?}

TMPYML=$(tempfile)
TMPSRC=$(tempfile)
TMPDST=$(tempfile)

sed -n '/---/,/^---$/p' $SRC > $TMPYML
sed '/---/,/^---$/d' $SRC > $TMPSRC

txt2tags -H -t html -i $TMPSRC -o $TMPDST

(
cat $TMPYML
echo '<notextile>'
cat $TMPDST
echo '</notextile>'
)> $DST

rm -f $TMPYML $TMPSRC $TMPDST

