#!/bin/sh

SRC=${1?}
DST=${2?}

TMPYML=$(tempfile -d .)
TMPSRC=$(tempfile -d .)
TMPDST=$(tempfile -d .)

sed -n '/---/,/^---$/p' $SRC > $TMPYML
sed '/---/,/^---$/d' $SRC > $TMPSRC

if ! txt2tags -H -t html -i $TMPSRC -o $TMPDST; then
	rm -f $TMPYML $TMPSRC $TMPDST
	exit 1
fi

(
cat $TMPYML
echo '<notextile>'
cat $TMPDST
echo '</notextile>'
)> $DST

rm -f $TMPYML $TMPSRC $TMPDST

