#!/usr/bin/python

import sys
import os
import yaml
from optparse import OptionParser

def main():
    parser = OptionParser("usage: %prog <output.t2t> <articles directories...>")

    opts, args = parser.parse_args()
    if len(args) < 2:
        parser.error("wrong number of arguments")
    outputfilename = args[0]

    articlesdir = sys.argv[2:]
    articlesinfo = []

    for a in articlesdir:
        info = a
        base = ''.join(a.split('/')[1])
        y = yaml.load(open(info).read())
        if y.get('disabled', False):
            continue
        articlesinfo.append(((y['date'], y['title'], base), y['tags']))
    articlesinfo.sort()
    articlesinfo.reverse()

    fd = open('%s.tmp' % outputfilename, 'w')
    fd.write('''Articles




The following articles are present in this page:
''')

    for a in articlesinfo:
        fd.write('- %s [%s %s/index.html]' % a[0])
        first = True
        for t in a[1]:
            if not first:
                fd.write(', ')
            else:
                fd.write(' ')
            first = False
            fd.write('//%s//' % t)
        fd.write('\n\n')

    fd.write('\n\n')

    fd.close()
    os.rename('%s.tmp' % outputfilename, outputfilename)


if __name__ == "__main__":
    main()

