
import os
import glob

Import(['env'])

articles = []

# Articles:
for i in glob.glob('*'):
    if not os.path.isdir(i):
        continue
    env.SConscript('%s/SConscript' % i)
    articles.append('%s/index.t2t' % i)
    env.Depends('%s/index.html' % i, 'index.t2t')

# Index:
indexbuild = env.File('indexbuild')
env.Command('index.t2t', articles, indexbuild.abspath + ' $TARGET $SOURCES')

env.MAKOHTML('index.t2t', MAKOFLAGS = '-t base')
env.Depends('index.html', '../index.t2t')

