---
name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: ./.github/actions/build
  build-deploy:
    if: github.ref == 'refs/heads/publish'
    needs:
      - build
      - omnilint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: ./.github/actions/build
      - run: rm -f .gitignore
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@v4.6.3
        with:
          branch: master
          folder: .
          single-commit: true
          clean: true
  omnilint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: docker://lpenz/omnilint:0.5.2
