---
name: CI
on: [workflow_dispatch, push, pull_request]  # yamllint disable-line rule:truthy
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0
      - uses: ./.github/actions/build
  build-deploy:
    if: github.ref == 'refs/heads/publish'
    needs: [build, omnilint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0
      - uses: ./.github/actions/build
      - run: rm -f .gitignore
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@v4.8.0
        with:
          branch: master
          folder: .
          single-commit: true
          clean: true
  rust-snippets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0
      - uses: dtolnay/rust-toolchain@stable
      - run: >
          set -e -x;
          cd articles/rust-snippets/snippets/;
          cargo test;
          cargo clippy;
          cargo fmt --check;
  rust-snippets-async:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0
      - uses: dtolnay/rust-toolchain@stable
      - run: >
          set -e -x;
          cd articles/rust-snippets/snippets-async/;
          cargo test;
          cargo clippy;
          cargo fmt --check;
  omnilint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0
      - uses: docker://lpenz/omnilint:0.5.2
